version: "3.8"

include:
  - casts_db/casts_db.yml
  - kafka-cluster/kafka-cluster.yml

networks:
  admin_casts_service_network:
    name: "admin_casts_service_net"
    driver: bridge

services:
  admin_casts_service:
    build:
      dockerfile: alpine.Dockerfile
    command: ./bin/app
    volumes:
      - ./docker/containers-configs/:/configs
    ports:
      - 9002:8080
    networks:
      - admin_casts_service_network
      - casts_db_network
      #- kafka_network
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
    #depends_on:
    # casts_pool:
    #  condition: service_started
    #kafka:
    #   condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider 'http://localhost:7001/healthcheck' || exit 1
      interval: 40s
      timeout: 20s
      retries: 3
      start_period: 20s
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: unless-stopped
    labels:
      servicename: "admin_casts_service"
      org.label-schema.group: "monitoring"
