// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: admin_casts_service_v1_messages.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserErrorMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UserErrorMessage) Reset() {
	*x = UserErrorMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_casts_service_v1_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserErrorMessage) ProtoMessage() {}

func (x *UserErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_admin_casts_service_v1_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserErrorMessage.ProtoReflect.Descriptor instead.
func (*UserErrorMessage) Descriptor() ([]byte, []int) {
	return file_admin_casts_service_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *UserErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetCastsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// use ',' as separator for multiple ids, or leave it blank if you want to get all the casts on the page
	MoviesIDs string `protobuf:"bytes,1,opt,name=MoviesIDs,json=movies_ids,proto3" json:"MoviesIDs,omitempty"`
	// must be in range 10-100
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// must be > 0
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *GetCastsRequest) Reset() {
	*x = GetCastsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_casts_service_v1_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCastsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCastsRequest) ProtoMessage() {}

func (x *GetCastsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_casts_service_v1_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCastsRequest.ProtoReflect.Descriptor instead.
func (*GetCastsRequest) Descriptor() ([]byte, []int) {
	return file_admin_casts_service_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *GetCastsRequest) GetMoviesIDs() string {
	if x != nil {
		return x.MoviesIDs
	}
	return ""
}

func (x *GetCastsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetCastsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type Casts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Casts []*Cast `protobuf:"bytes,1,rep,name=casts,proto3" json:"casts,omitempty"`
}

func (x *Casts) Reset() {
	*x = Casts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_casts_service_v1_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Casts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Casts) ProtoMessage() {}

func (x *Casts) ProtoReflect() protoreflect.Message {
	mi := &file_admin_casts_service_v1_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Casts.ProtoReflect.Descriptor instead.
func (*Casts) Descriptor() ([]byte, []int) {
	return file_admin_casts_service_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Casts) GetCasts() []*Cast {
	if x != nil {
		return x.Casts
	}
	return nil
}

type Profession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   int32  `protobuf:"varint,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Profession) Reset() {
	*x = Profession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_casts_service_v1_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Profession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profession) ProtoMessage() {}

func (x *Profession) ProtoReflect() protoreflect.Message {
	mi := &file_admin_casts_service_v1_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profession.ProtoReflect.Descriptor instead.
func (*Profession) Descriptor() ([]byte, []int) {
	return file_admin_casts_service_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Profession) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Profession) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Person struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         int32       `protobuf:"varint,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	Profession *Profession `protobuf:"bytes,2,opt,name=profession,proto3" json:"profession,omitempty"`
}

func (x *Person) Reset() {
	*x = Person{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_casts_service_v1_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_admin_casts_service_v1_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_admin_casts_service_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *Person) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Person) GetProfession() *Profession {
	if x != nil {
		return x.Profession
	}
	return nil
}

type Cast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieID   int32     `protobuf:"varint,1,opt,name=MovieID,json=movie_id,proto3" json:"MovieID,omitempty"`
	CastLabel string    `protobuf:"bytes,2,opt,name=CastLabel,json=cast_label,proto3" json:"CastLabel,omitempty"`
	Persons   []*Person `protobuf:"bytes,3,rep,name=Persons,json=persons,proto3" json:"Persons,omitempty"`
}

func (x *Cast) Reset() {
	*x = Cast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_casts_service_v1_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cast) ProtoMessage() {}

func (x *Cast) ProtoReflect() protoreflect.Message {
	mi := &file_admin_casts_service_v1_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cast.ProtoReflect.Descriptor instead.
func (*Cast) Descriptor() ([]byte, []int) {
	return file_admin_casts_service_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *Cast) GetMovieID() int32 {
	if x != nil {
		return x.MovieID
	}
	return 0
}

func (x *Cast) GetCastLabel() string {
	if x != nil {
		return x.CastLabel
	}
	return ""
}

func (x *Cast) GetPersons() []*Person {
	if x != nil {
		return x.Persons
	}
	return nil
}

type Professions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Professions []*Profession `protobuf:"bytes,1,rep,name=professions,proto3" json:"professions,omitempty"`
}

func (x *Professions) Reset() {
	*x = Professions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_casts_service_v1_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Professions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Professions) ProtoMessage() {}

func (x *Professions) ProtoReflect() protoreflect.Message {
	mi := &file_admin_casts_service_v1_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Professions.ProtoReflect.Descriptor instead.
func (*Professions) Descriptor() ([]byte, []int) {
	return file_admin_casts_service_v1_messages_proto_rawDescGZIP(), []int{6}
}

func (x *Professions) GetProfessions() []*Profession {
	if x != nil {
		return x.Professions
	}
	return nil
}

type GetCastRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieId int32 `protobuf:"varint,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
}

func (x *GetCastRequest) Reset() {
	*x = GetCastRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_casts_service_v1_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCastRequest) ProtoMessage() {}

func (x *GetCastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_casts_service_v1_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCastRequest.ProtoReflect.Descriptor instead.
func (*GetCastRequest) Descriptor() ([]byte, []int) {
	return file_admin_casts_service_v1_messages_proto_rawDescGZIP(), []int{7}
}

func (x *GetCastRequest) GetMovieId() int32 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

type CreateProfessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateProfessionRequest) Reset() {
	*x = CreateProfessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_casts_service_v1_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateProfessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfessionRequest) ProtoMessage() {}

func (x *CreateProfessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_casts_service_v1_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfessionRequest.ProtoReflect.Descriptor instead.
func (*CreateProfessionRequest) Descriptor() ([]byte, []int) {
	return file_admin_casts_service_v1_messages_proto_rawDescGZIP(), []int{8}
}

func (x *CreateProfessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateProfessionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateProfessionResponse) Reset() {
	*x = CreateProfessionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_casts_service_v1_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateProfessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfessionResponse) ProtoMessage() {}

func (x *CreateProfessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_casts_service_v1_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfessionResponse.ProtoReflect.Descriptor instead.
func (*CreateProfessionResponse) Descriptor() ([]byte, []int) {
	return file_admin_casts_service_v1_messages_proto_rawDescGZIP(), []int{9}
}

func (x *CreateProfessionResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateProfessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UpdateProfessionRequest) Reset() {
	*x = UpdateProfessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_casts_service_v1_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateProfessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfessionRequest) ProtoMessage() {}

func (x *UpdateProfessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_casts_service_v1_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfessionRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfessionRequest) Descriptor() ([]byte, []int) {
	return file_admin_casts_service_v1_messages_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateProfessionRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProfessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteProfessionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteProfessionRequest) Reset() {
	*x = DeleteProfessionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_casts_service_v1_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteProfessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfessionRequest) ProtoMessage() {}

func (x *DeleteProfessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_casts_service_v1_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteProfessionRequest) Descriptor() ([]byte, []int) {
	return file_admin_casts_service_v1_messages_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteProfessionRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CastLabel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieID   int32  `protobuf:"varint,1,opt,name=MovieID,json=movie_id,proto3" json:"MovieID,omitempty"`
	CastLabel string `protobuf:"bytes,2,opt,name=CastLabel,json=cast_label,proto3" json:"CastLabel,omitempty"`
}

func (x *CastLabel) Reset() {
	*x = CastLabel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_casts_service_v1_messages_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CastLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastLabel) ProtoMessage() {}

func (x *CastLabel) ProtoReflect() protoreflect.Message {
	mi := &file_admin_casts_service_v1_messages_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastLabel.ProtoReflect.Descriptor instead.
func (*CastLabel) Descriptor() ([]byte, []int) {
	return file_admin_casts_service_v1_messages_proto_rawDescGZIP(), []int{12}
}

func (x *CastLabel) GetMovieID() int32 {
	if x != nil {
		return x.MovieID
	}
	return 0
}

func (x *CastLabel) GetCastLabel() string {
	if x != nil {
		return x.CastLabel
	}
	return ""
}

type CastsLabels struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Casts []*CastLabel `protobuf:"bytes,1,rep,name=casts,proto3" json:"casts,omitempty"`
}

func (x *CastsLabels) Reset() {
	*x = CastsLabels{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_casts_service_v1_messages_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CastsLabels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastsLabels) ProtoMessage() {}

func (x *CastsLabels) ProtoReflect() protoreflect.Message {
	mi := &file_admin_casts_service_v1_messages_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastsLabels.ProtoReflect.Descriptor instead.
func (*CastsLabels) Descriptor() ([]byte, []int) {
	return file_admin_casts_service_v1_messages_proto_rawDescGZIP(), []int{13}
}

func (x *CastsLabels) GetCasts() []*CastLabel {
	if x != nil {
		return x.Casts
	}
	return nil
}

type SearchCastByLabelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// must be in range 10-100
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// must be > 0
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *SearchCastByLabelRequest) Reset() {
	*x = SearchCastByLabelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_casts_service_v1_messages_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchCastByLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCastByLabelRequest) ProtoMessage() {}

func (x *SearchCastByLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_casts_service_v1_messages_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCastByLabelRequest.ProtoReflect.Descriptor instead.
func (*SearchCastByLabelRequest) Descriptor() ([]byte, []int) {
	return file_admin_casts_service_v1_messages_proto_rawDescGZIP(), []int{14}
}

func (x *SearchCastByLabelRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SearchCastByLabelRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchCastByLabelRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type PersonParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProfessionID int32 `protobuf:"varint,2,opt,name=professionID,json=profession_id,proto3" json:"professionID,omitempty"`
}

func (x *PersonParam) Reset() {
	*x = PersonParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_casts_service_v1_messages_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonParam) ProtoMessage() {}

func (x *PersonParam) ProtoReflect() protoreflect.Message {
	mi := &file_admin_casts_service_v1_messages_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonParam.ProtoReflect.Descriptor instead.
func (*PersonParam) Descriptor() ([]byte, []int) {
	return file_admin_casts_service_v1_messages_proto_rawDescGZIP(), []int{15}
}

func (x *PersonParam) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PersonParam) GetProfessionID() int32 {
	if x != nil {
		return x.ProfessionID
	}
	return 0
}

type CreateCastRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CastLabel string         `protobuf:"bytes,1,opt,name=CastLabel,json=cast_label,proto3" json:"CastLabel,omitempty"`
	MovieID   int32          `protobuf:"varint,2,opt,name=MovieID,json=movie_id,proto3" json:"MovieID,omitempty"`
	Persons   []*PersonParam `protobuf:"bytes,3,rep,name=Persons,json=persons,proto3" json:"Persons,omitempty"`
}

func (x *CreateCastRequest) Reset() {
	*x = CreateCastRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_casts_service_v1_messages_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCastRequest) ProtoMessage() {}

func (x *CreateCastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_casts_service_v1_messages_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCastRequest.ProtoReflect.Descriptor instead.
func (*CreateCastRequest) Descriptor() ([]byte, []int) {
	return file_admin_casts_service_v1_messages_proto_rawDescGZIP(), []int{16}
}

func (x *CreateCastRequest) GetCastLabel() string {
	if x != nil {
		return x.CastLabel
	}
	return ""
}

func (x *CreateCastRequest) GetMovieID() int32 {
	if x != nil {
		return x.MovieID
	}
	return 0
}

func (x *CreateCastRequest) GetPersons() []*PersonParam {
	if x != nil {
		return x.Persons
	}
	return nil
}

type UpdateLabelForCastRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label   string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	MovieID int32  `protobuf:"varint,2,opt,name=MovieID,json=movie_id,proto3" json:"MovieID,omitempty"`
}

func (x *UpdateLabelForCastRequest) Reset() {
	*x = UpdateLabelForCastRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_casts_service_v1_messages_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLabelForCastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLabelForCastRequest) ProtoMessage() {}

func (x *UpdateLabelForCastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_casts_service_v1_messages_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLabelForCastRequest.ProtoReflect.Descriptor instead.
func (*UpdateLabelForCastRequest) Descriptor() ([]byte, []int) {
	return file_admin_casts_service_v1_messages_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateLabelForCastRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *UpdateLabelForCastRequest) GetMovieID() int32 {
	if x != nil {
		return x.MovieID
	}
	return 0
}

type AddPersonsToTheCastRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieID int32          `protobuf:"varint,1,opt,name=MovieID,json=movie_id,proto3" json:"MovieID,omitempty"`
	Persons []*PersonParam `protobuf:"bytes,2,rep,name=Persons,json=persons,proto3" json:"Persons,omitempty"`
}

func (x *AddPersonsToTheCastRequest) Reset() {
	*x = AddPersonsToTheCastRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_casts_service_v1_messages_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPersonsToTheCastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPersonsToTheCastRequest) ProtoMessage() {}

func (x *AddPersonsToTheCastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_casts_service_v1_messages_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPersonsToTheCastRequest.ProtoReflect.Descriptor instead.
func (*AddPersonsToTheCastRequest) Descriptor() ([]byte, []int) {
	return file_admin_casts_service_v1_messages_proto_rawDescGZIP(), []int{18}
}

func (x *AddPersonsToTheCastRequest) GetMovieID() int32 {
	if x != nil {
		return x.MovieID
	}
	return 0
}

func (x *AddPersonsToTheCastRequest) GetPersons() []*PersonParam {
	if x != nil {
		return x.Persons
	}
	return nil
}

type RemovePersonsFromTheCastRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieID int32          `protobuf:"varint,1,opt,name=MovieID,json=movie_id,proto3" json:"MovieID,omitempty"`
	Persons []*PersonParam `protobuf:"bytes,2,rep,name=Persons,json=persons,proto3" json:"Persons,omitempty"`
}

func (x *RemovePersonsFromTheCastRequest) Reset() {
	*x = RemovePersonsFromTheCastRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_casts_service_v1_messages_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemovePersonsFromTheCastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePersonsFromTheCastRequest) ProtoMessage() {}

func (x *RemovePersonsFromTheCastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_casts_service_v1_messages_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePersonsFromTheCastRequest.ProtoReflect.Descriptor instead.
func (*RemovePersonsFromTheCastRequest) Descriptor() ([]byte, []int) {
	return file_admin_casts_service_v1_messages_proto_rawDescGZIP(), []int{19}
}

func (x *RemovePersonsFromTheCastRequest) GetMovieID() int32 {
	if x != nil {
		return x.MovieID
	}
	return 0
}

func (x *RemovePersonsFromTheCastRequest) GetPersons() []*PersonParam {
	if x != nil {
		return x.Persons
	}
	return nil
}

type DeleteCastRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MovieId int32 `protobuf:"varint,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
}

func (x *DeleteCastRequest) Reset() {
	*x = DeleteCastRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_admin_casts_service_v1_messages_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCastRequest) ProtoMessage() {}

func (x *DeleteCastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_casts_service_v1_messages_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCastRequest.ProtoReflect.Descriptor instead.
func (*DeleteCastRequest) Descriptor() ([]byte, []int) {
	return file_admin_casts_service_v1_messages_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteCastRequest) GetMovieId() int32 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

var File_admin_casts_service_v1_messages_proto protoreflect.FileDescriptor

var file_admin_casts_service_v1_messages_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x63, 0x61, 0x73, 0x74, 0x73, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x31, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x63,
	0x61, 0x73, 0x74, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x2c, 0x0a, 0x10,
	0x55, 0x73, 0x65, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x5a, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x43, 0x61, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x09, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x49, 0x44, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x73, 0x5f, 0x69, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x38, 0x0a, 0x05, 0x43, 0x61, 0x73, 0x74, 0x73, 0x12,
	0x2f, 0x0a, 0x05, 0x63, 0x61, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x63, 0x61, 0x73, 0x74, 0x73, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x61, 0x73, 0x74, 0x52, 0x05, 0x63, 0x61, 0x73, 0x74, 0x73,
	0x22, 0x30, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x59, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3f, 0x0a, 0x0a,
	0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x63, 0x61, 0x73, 0x74, 0x73, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x77, 0x0a,
	0x04, 0x43, 0x61, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x07, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x69, 0x64,
	0x12, 0x1d, 0x0a, 0x09, 0x43, 0x61, 0x73, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x73, 0x74, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12,
	0x35, 0x0a, 0x07, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x63, 0x61, 0x73, 0x74, 0x73, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52, 0x07, 0x70,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x22, 0x50, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x41, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x5f, 0x63, 0x61, 0x73, 0x74, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x70, 0x72, 0x6f,
	0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x2b, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43,
	0x61, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x6f,
	0x76, 0x69, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x6f,
	0x76, 0x69, 0x65, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2a, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72,
	0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x3d, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x29, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x45, 0x0a, 0x09, 0x43, 0x61,
	0x73, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x19, 0x0a, 0x07, 0x4d, 0x6f, 0x76, 0x69, 0x65,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f,
	0x69, 0x64, 0x12, 0x1d, 0x0a, 0x09, 0x43, 0x61, 0x73, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x73, 0x74, 0x5f, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x22, 0x43, 0x0a, 0x0b, 0x43, 0x61, 0x73, 0x74, 0x73, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73,
	0x12, 0x34, 0x0a, 0x05, 0x63, 0x61, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x63, 0x61, 0x73, 0x74, 0x73, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x61, 0x73, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52,
	0x05, 0x63, 0x61, 0x73, 0x74, 0x73, 0x22, 0x5a, 0x0a, 0x18, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x43, 0x61, 0x73, 0x74, 0x42, 0x79, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x22, 0x42, 0x0a, 0x0b, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x23, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x66, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x22, 0x89, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x61, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x09,
	0x43, 0x61, 0x73, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x61, 0x73, 0x74, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x19, 0x0a, 0x07, 0x4d,
	0x6f, 0x76, 0x69, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x6f,
	0x76, 0x69, 0x65, 0x5f, 0x69, 0x64, 0x12, 0x3a, 0x0a, 0x07, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f,
	0x63, 0x61, 0x73, 0x74, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x07, 0x70, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x73, 0x22, 0x4c, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x62, 0x65,
	0x6c, 0x46, 0x6f, 0x72, 0x43, 0x61, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x19, 0x0a, 0x07, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x69, 0x64,
	0x22, 0x73, 0x0a, 0x1a, 0x41, 0x64, 0x64, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x54, 0x6f,
	0x54, 0x68, 0x65, 0x43, 0x61, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x07, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x69, 0x64, 0x12, 0x3a, 0x0a, 0x07, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x5f, 0x63, 0x61, 0x73, 0x74, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x07, 0x70, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x73, 0x22, 0x78, 0x0a, 0x1f, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x68, 0x65, 0x43, 0x61, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x07, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x6f, 0x76, 0x69, 0x65,
	0x5f, 0x69, 0x64, 0x12, 0x3a, 0x0a, 0x07, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x63, 0x61, 0x73,
	0x74, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x07, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x22,
	0x2e, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x49, 0x64, 0x42,
	0x1f, 0x5a, 0x1d, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x63, 0x61, 0x73, 0x74, 0x73, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_admin_casts_service_v1_messages_proto_rawDescOnce sync.Once
	file_admin_casts_service_v1_messages_proto_rawDescData = file_admin_casts_service_v1_messages_proto_rawDesc
)

func file_admin_casts_service_v1_messages_proto_rawDescGZIP() []byte {
	file_admin_casts_service_v1_messages_proto_rawDescOnce.Do(func() {
		file_admin_casts_service_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_admin_casts_service_v1_messages_proto_rawDescData)
	})
	return file_admin_casts_service_v1_messages_proto_rawDescData
}

var file_admin_casts_service_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_admin_casts_service_v1_messages_proto_goTypes = []interface{}{
	(*UserErrorMessage)(nil),                // 0: admin_casts_service.UserErrorMessage
	(*GetCastsRequest)(nil),                 // 1: admin_casts_service.GetCastsRequest
	(*Casts)(nil),                           // 2: admin_casts_service.Casts
	(*Profession)(nil),                      // 3: admin_casts_service.Profession
	(*Person)(nil),                          // 4: admin_casts_service.Person
	(*Cast)(nil),                            // 5: admin_casts_service.Cast
	(*Professions)(nil),                     // 6: admin_casts_service.Professions
	(*GetCastRequest)(nil),                  // 7: admin_casts_service.GetCastRequest
	(*CreateProfessionRequest)(nil),         // 8: admin_casts_service.CreateProfessionRequest
	(*CreateProfessionResponse)(nil),        // 9: admin_casts_service.CreateProfessionResponse
	(*UpdateProfessionRequest)(nil),         // 10: admin_casts_service.UpdateProfessionRequest
	(*DeleteProfessionRequest)(nil),         // 11: admin_casts_service.DeleteProfessionRequest
	(*CastLabel)(nil),                       // 12: admin_casts_service.CastLabel
	(*CastsLabels)(nil),                     // 13: admin_casts_service.CastsLabels
	(*SearchCastByLabelRequest)(nil),        // 14: admin_casts_service.SearchCastByLabelRequest
	(*PersonParam)(nil),                     // 15: admin_casts_service.PersonParam
	(*CreateCastRequest)(nil),               // 16: admin_casts_service.CreateCastRequest
	(*UpdateLabelForCastRequest)(nil),       // 17: admin_casts_service.UpdateLabelForCastRequest
	(*AddPersonsToTheCastRequest)(nil),      // 18: admin_casts_service.AddPersonsToTheCastRequest
	(*RemovePersonsFromTheCastRequest)(nil), // 19: admin_casts_service.RemovePersonsFromTheCastRequest
	(*DeleteCastRequest)(nil),               // 20: admin_casts_service.DeleteCastRequest
}
var file_admin_casts_service_v1_messages_proto_depIdxs = []int32{
	5,  // 0: admin_casts_service.Casts.casts:type_name -> admin_casts_service.Cast
	3,  // 1: admin_casts_service.Person.profession:type_name -> admin_casts_service.Profession
	4,  // 2: admin_casts_service.Cast.Persons:type_name -> admin_casts_service.Person
	3,  // 3: admin_casts_service.Professions.professions:type_name -> admin_casts_service.Profession
	12, // 4: admin_casts_service.CastsLabels.casts:type_name -> admin_casts_service.CastLabel
	15, // 5: admin_casts_service.CreateCastRequest.Persons:type_name -> admin_casts_service.PersonParam
	15, // 6: admin_casts_service.AddPersonsToTheCastRequest.Persons:type_name -> admin_casts_service.PersonParam
	15, // 7: admin_casts_service.RemovePersonsFromTheCastRequest.Persons:type_name -> admin_casts_service.PersonParam
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_admin_casts_service_v1_messages_proto_init() }
func file_admin_casts_service_v1_messages_proto_init() {
	if File_admin_casts_service_v1_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_admin_casts_service_v1_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserErrorMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_casts_service_v1_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCastsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_casts_service_v1_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Casts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_casts_service_v1_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Profession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_casts_service_v1_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_casts_service_v1_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_casts_service_v1_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Professions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_casts_service_v1_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCastRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_casts_service_v1_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateProfessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_casts_service_v1_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateProfessionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_casts_service_v1_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateProfessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_casts_service_v1_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteProfessionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_casts_service_v1_messages_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CastLabel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_casts_service_v1_messages_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CastsLabels); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_casts_service_v1_messages_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchCastByLabelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_casts_service_v1_messages_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_casts_service_v1_messages_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCastRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_casts_service_v1_messages_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLabelForCastRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_casts_service_v1_messages_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPersonsToTheCastRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_casts_service_v1_messages_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemovePersonsFromTheCastRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_admin_casts_service_v1_messages_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCastRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_admin_casts_service_v1_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_admin_casts_service_v1_messages_proto_goTypes,
		DependencyIndexes: file_admin_casts_service_v1_messages_proto_depIdxs,
		MessageInfos:      file_admin_casts_service_v1_messages_proto_msgTypes,
	}.Build()
	File_admin_casts_service_v1_messages_proto = out.File
	file_admin_casts_service_v1_messages_proto_rawDesc = nil
	file_admin_casts_service_v1_messages_proto_goTypes = nil
	file_admin_casts_service_v1_messages_proto_depIdxs = nil
}
